# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ApptNiJdVmatgpBrsxzItpP-Wu_FIdQ
"""

#find missing
list1 = [1,2,3,4,5,6]
list2 = [2,3,1,0,6,7]
n=[]
for i in list1:
  if i not in list2:
    print(i)

#report card
marks =  [
          [78, 76, 94, 86, 88],
          [91, 71, 98, 65],
          [95, 45, 78],
          [87, 67, 49, 68, 88]]
#sum=0
average=0
for i in range(0,len(marks)):
  average=0
  for j in range(0,len(marks[i])):
    average+=marks[i][j]//len(marks[i])                   #marks[i][j] for getting elements of nested list
  print(i+1,"year average",average)

number = 30
n = [10, 11, 12, 13, 14, 17, 18, 19]
sum=0
new=[]
i=0
j=0
for i in range(i,len(n)):
  sum=0
  for j in range(i+1,len(n)):                         #twist- take range as i+1 insted of 0 to avoid repetative elements
    sum=n[i]+n[j]                                     # if we start from 0 then loop will start from 0 again n again
    if sum==30:
      new.append([n[i],n[j]])
    else:
        sum=0
print(new)

elements = [23, 14, 56, 12, 19, 9, 15, 25, 31, 42, 43]
count_even=0
count_odd=0
for i in elements:
  if i%2==0:
    count_even+=1
  else:
    count_odd+=1
print("even count",count_even,"\nodd count",count_odd )

elements = [23, 14, 56, 12, 19, 9, 15, 25, 31, 42, 43]
sum_even=0
sum_odd=0
for i in elements:
  if i%2==0:
    sum_even+=i
  else:
    sum_odd+=i
print("even sum",sum_even,"\nodd sum",sum_odd )

#lakhpati
kitna_paisa_hai = [3000, 600000, 324990909, 90990900, 30000, 5600000, 690909090, 31010101, 532010, 510, 4100]
c,l,d=0,0,0
for i in kitna_paisa_hai:
  if i>=10000000:
   c+=1
  elif i>=100000:
    l+=1
  else:
    d+=1
print(c,l,d)

#duplicates   #make new list add items one by one, check if item is already there then add in another list
n = [19, 17, 12, 17, 17, 18, 10, 17, 14, 12, 19, 17, 12, 13, 11]              
new=[]
dup=[]
for j in n:
  if j not in new:
    new.append(j)
  else:
    dup.append(j)
print("list with no duplicated",new,"\nList with dupliacte items",dup)

char = ["a", "n", "t", "a", "a", "t", "n", "n", "a", "x", "u", "g", "a", "x", "a"]
i=0
L=[]
while i<len(char):
    count=0
    L2=[]
    j=0
    while j<len(char):
            if char[i]==char[j]:
              
            j+=1
    L2.append(char[i])
    L2.append(count)
    if L2 not in L:
        L.append(L2)

    i+=1
print(L,end=" ")

#my code count occurences
char_list = ["a", "n", "t", "a", "a", "t", "n", "n", "a", "x", "u", "g", "a", "x", "a"]
list1=[]
for i in char_list:
  count=0
  list2=[]
  for j in char_list:
    if j==i:
      count+=1
  list2.append(i)
  list2.append(count)
  if list2 not in list1:
    list1.append(list2)
print(list1,end="")

#remove substring
mainStr = "the quick brown fox jumped over the lazy dog. The dog slept over the verandah."
subStr = "over"
replaceStr="on"
mainStr=mainStr.split( )
l=[]
for i in mainStr:
  if i=="over":
    continue                         #use continue only for removing
  else:
    l.append(i)
    print(i,end=" ")
    
#second part
for i in mainStr:
  if i=="over":
    i="on"
  print(i,end=" ")

n = [19, 17, 12, 17, 17, 18, 10, 17, 14, 12, 19, 17, 12, 13, 11]
#for ascending
for j in range(len(n)):
  i=j+1
  for i in range(len(n)):
    if n[j]<n[i]:
      n[j],n[i]=n[i],n[j]
print(n)


#for descending
for j in range(len(n)):
  i=j+1
  for i in range(len(n)):
    if n[j]>n[i]:
      n[j],n[i]=n[i],n[j]
print(n)













